---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: team-a-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: team-a-mcp.{{ .Values.clusterSubdomain }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: mcp
  to:
    kind: Service
    name: team-a-gateway-openshift-default
    weight: 100
