{{- if .Values.pullSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: acs-nightly-pull-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.pullSecret }}
{{- end }}
