{{- if .Values.idms.enabled }}
---
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: lightspeed-operator-openshift-lightspeed-prod-to-ci
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-operator
    source: registry.redhat.io/openshift-lightspeed/lightspeed-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols-bundle
    source: registry.redhat.io/openshift-lightspeed/lightspeed-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-service
    source: registry.redhat.io/openshift-lightspeed/lightspeed-service-api-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/crt-nshift-lightspeed-tenant/ols/lightspeed-console
    source: registry.redhat.io/openshift-lightspeed/lightspeed-console-plugin-rhel9
{{- end }}
