subscription:
  channel: stable
  installPlanApproval: Automatic
  name: lightspeed-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  namespace: openshift-lightspeed

llm:
  apiUrl: ""
  apiKey: ""
  provider: openai
  model: qwen3-235b

featureGates:
  - MCPServer

mcpServer:
  name: openshift-mcp
  url: http://openshift-mcp-server.openshift-mcp.svc.cluster.local:8080/mcp
  timeout: 120

# TEMPORARY: Custom MCP server image for Perses integration
mcpImagePatch:
  csvName: lightspeed-operator.v1.1.1
  image: quay.io/tremes/ocp-mcp
