namespace: openshift-mcp
name: openshift-mcp-server
image: registry.redhat.io/openshift-lightspeed/openshift-mcp-server-rhel9@sha256:83f288c04aad9c742cf2cee51f45e1be1982e1fcc388d2112cf5483e381fff62

toolsets:
  - core
  - config
