subscription:
  channel: preview
  installPlanApproval: Automatic
  name: mcp-gateway
  source: redhat-operators
  sourceNamespace: openshift-marketplace

gateway:
  name: mcp-gateway
  namespace: openshift-ingress
  gatewayClassName: openshift-default
