subscription:
  channel: preview
  installPlanApproval: Automatic
  name: mcp-gateway
  source: redhat-operators
  sourceNamespace: openshift-marketplace

gateway:
  name: mcp-gateway
  namespace: openshift-ingress
  gatewayClassName: openshift-default
  tls:
    clusterIssuer: zerossl-production-aws

keycloak:
  realm: keycloak
  clientId: mcp-gateway
  clientSecret: mcp-gateway-secret
  users:
    - username: user1
      password: user1pass
      email: user1@example.com
      firstName: MCP
      lastName: User1
    - username: user2
      password: user2pass
      email: user2@example.com
      firstName: MCP
      lastName: User2
