---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-team-routes
  namespace: {{ .Release.Namespace }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: team-a-mcp
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: team-b-mcp
  to:
    - group: ""
      kind: Service
