vm:
  name: rhel9-vm
  instanceType: u1.medium
  preference: rhel.9
  diskSize: 30Gi
  running: true
  user: cloud-user
  password: ""
  roxagentVersion: "4.11.1"

bootSource:
  name: rhel9
  namespace: openshift-virtualization-os-images
