---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ .Values.vm.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instancetype:
    name: {{ .Values.vm.instanceType }}
  preference:
    name: {{ .Values.vm.preference }}
  running: {{ .Values.vm.running }}
  dataVolumeTemplates:
    - metadata:
        name: {{ .Values.vm.name }}-rootdisk
      spec:
        sourceRef:
          kind: DataSource
          name: {{ .Values.bootSource.name }}
          namespace: {{ .Values.bootSource.namespace }}
        storage:
          resources:
            requests:
              storage: {{ .Values.vm.diskSize }}
  template:
    spec:
      domain:
        devices: {}
      volumes:
        - dataVolume:
            name: {{ .Values.vm.name }}-rootdisk
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: {{ .Values.vm.user }}
              password: {{ .Values.vm.password }}
              chpasswd:
                expire: false
              ssh_pwauth: true
          name: cloudinitdisk
