{{- if .Values.acs.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" .Values.acs.name "namespace" .Values.argocd.namespace "syncWave" "0") }}
spec:
  destination:
    namespace: {{ .Values.acs.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: acs
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
    helm:
      valuesObject:
        acs-operator:
{{- if .Values.acs.pullSecret }}
          catalogSource:
            pullSecret: {{ .Values.acs.pullSecret }}
{{- end }}
        acs-instance:
          clusterName: {{ .Values.acs.clusterName }}
          adminPassword: {{ .Values.acs.adminPassword }}
{{- if .Values.acs.pullSecret }}
          pullSecret: {{ .Values.acs.pullSecret }}
{{- end }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
