{{- if .Values.openshiftAgenticLightspeed.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
{{ include "app-of-apps.metadata" (dict "name" "openshift-lightspeed-operator" "namespace" .Values.argocd.namespace "syncWave" "1") }}
spec:
  destination:
    namespace: {{ .Values.openshiftAgenticLightspeed.namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-lightspeed-operator
    repoURL: {{ .Values.gitops.repoURL }}
    targetRevision: {{ .Values.gitops.targetRevision }}
{{ include "app-of-apps.syncPolicy" . | indent 2 }}
{{- end }}
