{{- if .Values.agentic.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lightspeed-otel-collector-client
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data: {}
{{- end }}
