{{- if .Values.agentic.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lightspeed-agentic-console-plugin
  namespace: {{ .Values.subscription.namespace }}
  labels:
    app.kubernetes.io/name: lightspeed-agentic-console-plugin
    app.kubernetes.io/component: console
  annotations:
    argocd.argoproj.io/sync-wave: "6"
data:
  nginx.conf: |
    pid /tmp/nginx/nginx.pid;
    error_log /dev/stdout info;
    events {}
    http {
      client_body_temp_path /tmp/nginx/client_body;
      proxy_temp_path       /tmp/nginx/proxy;
      fastcgi_temp_path     /tmp/nginx/fastcgi;
      uwsgi_temp_path       /tmp/nginx/uwsgi;
      scgi_temp_path        /tmp/nginx/scgi;
      include               /etc/nginx/mime.types;
      default_type          application/octet-stream;
      keepalive_timeout     65;
      server {
        listen              9443 ssl;
        listen              [::]:9443 ssl;
        ssl_certificate     /var/cert/tls.crt;
        ssl_certificate_key /var/cert/tls.key;
        root                /usr/share/nginx/html;
        access_log          /dev/stdout;
      }
    }
{{- end }}
