---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-lightspeed
  namespace: {{ .Values.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  targetNamespaces:
    - {{ .Values.subscription.namespace }}
