---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-config
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    toolsets = [{{- range $i, $t := .Values.toolsets }}{{- if $i }},{{ end }}"{{ $t }}"{{- end }}]
    log_level = 0
    port = "8080"
    read_only = true
